POST http://localhost:8080/users/register
Content-Type: application/json

{
  "email":"banana@gmail.com",
  "user":"banani",
  "password":"banana123"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email":"banana@gmail.com",
  "password":"banana123"
}

###
POST http://localhost:8080/users/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQ3aEFpQzZBczVOczZuLzF2aHB0SzcuUUJuZDFNek1DekZ5VDNZLkJVdXZBY28ucldpNVl5SyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg0NDgzNTl9.QHbfhfwnKNMaO0vfJmAosuhWvR4DzMCu-gzlfM1atE0"
}

###
POST http://localhost:8080/users/tokenValidate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQ3aEFpQzZBczVOczZuLzF2aHB0SzcuUUJuZDFNek1DekZ5VDNZLkJVdXZBY28ucldpNVl5SyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2Mzg0NDgzNTl9.QHbfhfwnKNMaO0vfJmAosuhWvR4DzMCu-gzlfM1atE0

###
GET http://localhost:8080/api/v1/information
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRvdFpHTUVRcHY0aDNteWZPYjRweUh1T3JIcmxiNFJpUFIwQnNWNnM1ZGp1QnZsWG5EeUhNeSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgzOTMwODUsImV4cCI6MTYzODM5MzA5NX0.noV5AVW2XUtSO8PP_UarjJ7gryzgBvSZ5I1zx_pkYcw

###
GET http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkRFFna3F3SG1MZ2NLdmRGT3NrblguVlJIRWgzY3ZQUGxyMjQuOFZYZ09wTmNWd0NNOExJeSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgzOTIyOTUsImV4cCI6MTYzODM5MjMwNX0.p14AabBcuQliGs6txtAr85qvIMW3jF5iPlvHvhHxc1Q


