POST http://localhost:8080/users/register
Content-Type: application/json

{
  "email":"banana@gmail.com",
  "user":"banani",
  "password":"banana123"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email":"banana@gmail.com",
  "password":"banana123"
}

###
POST http://localhost:8080/users/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRvdFpHTUVRcHY0aDNteWZPYjRweUh1T3JIcmxiNFJpUFIwQnNWNnM1ZGp1QnZsWG5EeUhNeSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgzOTMwODV9.IT7uu1t1F5s9FRir2ffVwaz5hiGDZVqxqIlbLg54wFk"
}

###
POST http://localhost:8080/users/tokenValidate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRjV2k1cENTLjA5Sm1lNG9lZjRzbjguZ1M2djdBZmhVdHh2ejdXWXNDeFJtWHdaZU5jWFZwVyIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgzODg3NjEsImV4cCI6MTYzODM4ODc3MX0.MMPXXC2MkYDqzsxmb8f_MWHI71SKmQvLLxXWUpcP1Rk

###
GET http://localhost:8080/api/v1/information
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkRFFna3F3SG1MZ2NLdmRGT3NrblguVlJIRWgzY3ZQUGxyMjQuOFZYZ09wTmNWd0NNOExJeSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgzOTIyOTUsImV4cCI6MTYzODM5MjMwNX0.p14AabBcuQliGs6txtAr85qvIMW3jF5iPlvHvhHxc1Q

###
GET http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJhbmFuYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRkRFFna3F3SG1MZ2NLdmRGT3NrblguVlJIRWgzY3ZQUGxyMjQuOFZYZ09wTmNWd0NNOExJeSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MzgzOTIyOTUsImV4cCI6MTYzODM5MjMwNX0.p14AabBcuQliGs6txtAr85qvIMW3jF5iPlvHvhHxc1Q


